---
version: 2
updates:
  # actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # app
  - package-ecosystem: docker
    directory: /app
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /app
    schedule:
      interval: daily

  # api
  - package-ecosystem: docker
    directory: /api
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /api
    schedule:
      interval: daily

  # database
  - package-ecosystem: docker
    directory: /database
    schedule:
      interval: daily

  # agent
  - package-ecosystem: docker
    directory: /agent
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /agent
    schedule:
      interval: daily

  # worker
  - package-ecosystem: docker
    directory: /worker
    schedule:
      interval: daily
