---
version: "2"

volumes:
  database-data:
  worker-data:

services:
  agent:
    build: ./agent
    depends_on:
      - api
      - worker
    labels:
      io.balena.features.supervisor-api: 1  
    network_mode: host
    restart: always

  api:
    build: ./api
    depends_on:
      - database
    ports:
      - 8080:8080
    network_mode: host
    restart: always

  app:
    build: ./app
    depends_on:
      - api
    ports:
      - 80:80
    network_mode: host
    restart: always

  database:
    build: ./database
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    network_mode: host
    restart: always

  worker:
    build: ./worker
    ports:
      - 31416:31416
    volumes:
      - worker-data:/var/lib/boinc
    network_mode: host
    restart: always

  wifi:
    build: ./wifi
    labels:
      io.balena.features.dbus: 1
      io.balena.features.firmware: 1
    cap_add:
      - NET_ADMIN
    network_mode: host
    restart: always
