---
version: "2"

volumes:
  database-data:
  worker-data:

services:
  agent:
    container_name: agent
    build: ./agent
    depends_on:
      - api
      - worker
    network_mode: host
    restart: always

  api:
    container_name: api
    build: ./api
    depends_on:
      - database
    ports:
      - 8080:8080
    network_mode: host
    restart: always

  app:
    container_name: app
    build: ./app
    depends_on:
      - api
    ports:
      - 80:80
    network_mode: host
    restart: always

  browser:
    container_name: browser
    image: balenablocks/browser:latest
    environment:
      - KIOSK=1
    privileged: true
    network_mode: host
    restart: always

  database:
    container_name: database
    build: ./database
    ports:
      - 5432:5432
    volumes:
      - database-data:/var/lib/postgresql/data
    network_mode: host
    restart: always

  hostname:
    container_name: hostname
    image: balenablocks/hostname:latest
    environment:
      SET_HOSTNAME: scitizen
    labels:
      io.balena.features.supervisor-api: 1
    network_mode: host
    restart: no

  worker:
    container_name: worker
    build: ./worker
    ports:
      - 31416:31416
    volumes:
      - worker-data:/var/lib/boinc
    network_mode: host
    restart: always
