---
name: 💡 Feature Request
description: Create a feature request for Scitizen
title: "[feat] <title>"
labels: [enhancement]
assignees: pcorbel
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a feature request! Please fill out this form as completely as possible.
  - type: textarea
    attributes:
      label: Describe the feature you would like to request
      description: A clear and concise description of what you want and what your use case is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you would like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternatives you have considered
      description: A clear and concise description of any alternative solutions or features you have considered.
    validations:
      required: true
  - type: markdown
    attributes:
      value: Before posting the feature request, go through the descriptions you've written down to make sure they are detailed and clear.
  - type: markdown
    attributes:
      value: Thanks in advance!
