FROM balenalib/%%BALENA_ARCH%%-debian-node:16.6.2-stretch-run

WORKDIR /app

COPY ./package.json /app/package.json
COPY ./yarn.lock /app/yarn.lock
RUN yarn install --pure-lockfile --network-timeout 3600000

COPY . /app/
RUN yarn build
CMD yarn start
