---
name: Push to BalenaCloud

on:
  push:
    branches: [main]

jobs:
  balena-push:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Push to BalenaCloud
        uses: amingilani/push-to-balenacloud@v1.0.1
        with:
          api-token: ${{ secrets.BALENA_API_TOKEN }}
          application-name: scitizen
